// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreasureHunt.Api.Database;

#nullable disable

namespace TreasureHunt.Api.Migrations
{
    [DbContext(typeof(TreasureHuntDbContext))]
    partial class TreasureHuntDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TreasureHunt.Api.Database.TreasureHuntLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("M")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatrixMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TreasureHuntLog");
                });
#pragma warning restore 612, 618
        }
    }
}
